# Generated by Django 3.2.4 on 2021-06-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.JSONField(max_length=200),
        ),
    ]
